// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/ListProduct/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ListProduct">> = Specific
  const handler = {} as typeof import("../../src/app/ListProduct/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Map">> = Specific
  const handler = {} as typeof import("../../src/app/Map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Software Support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Software Support">> = Specific
  const handler = {} as typeof import("../../src/app/Software Support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-us">> = Specific
  const handler = {} as typeof import("../../src/app/about-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/category/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/category">> = Specific
  const handler = {} as typeof import("../../src/app/category/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/category/tester-refill-showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/category/tester-refill-showcase">> = Specific
  const handler = {} as typeof import("../../src/app/category/tester-refill-showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../src/app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/software-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/software-support">> = Specific
  const handler = {} as typeof import("../../src/app/software-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/category-counts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/category-counts">> = Specific
  const handler = {} as typeof import("../../src/app/api/category-counts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/facebook-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facebook-metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/facebook-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/map-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/map-metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/map-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/perfumes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/perfumes">> = Specific
  const handler = {} as typeof import("../../src/app/api/perfumes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/site-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/site-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wholesale-signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wholesale-signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/wholesale-signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stats/facebook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/stats/facebook">> = Specific
  const handler = {} as typeof import("../../src/app/stats/facebook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stats/views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/stats/views">> = Specific
  const handler = {} as typeof import("../../src/app/stats/views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/track">> = Specific
  const handler = {} as typeof import("../../src/app/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
